### ISSUE TITLE
Can't connect to Emby with self signed certificate

### ISSUE THREAD

**Issue by lapoigne** [mregni/EmbyStat#1040]
# Bug report

**Describe the bug**
On the wizard I can't configure an https link to Emby server, the server is not found.
It's ok with http link.
The Emby server is on Synology NAS and EmbyStat on my machine.
Nothing in logs for https connection, but ok for http 'Connecting to ws://' line

**To Reproduce**

1. Go to 'http://127.0.01:6555/wizard'
2. Configure https connection
3. No Emby found

**Expected behavior**
Connection to Emby with API key

**System (please complete the following information):**

- OS: Ubuntu and Docker image
- Browser firefox
- Version 0.2.0-beta.14

**Comment by mregni** [comment]
You are sure you are using the correct port as well for https?
Can you see anything in the Emby logs about a ping call happening?

**Comment by lapoigne** [comment]
Yes I'm using the correct port, in doubt I tested the two ports for http and https.
Nothing in EmbyStat log and nothing in Emby log about an https connection.
I see EmbyStat log show only INFO messages, there is an option to show more DEBUG messages ?

**Comment by lapoigne** [comment]
I edited the usersettings.json file with
```
"ServerPort": 8920,
"ServerProtocol": 0
```

Now I can see in EmbyStat log the wss:// connection line, but it fail after some retry.
Nothing on Emby log, like EmbyStat don't send anything.

Tested on 2 computers with 2 different network to eliminate firewall problem.

**Comment by Happy2Play** [comment]
Had no issue adding my https connection information to EmbyStats and connection to my server.

Windows system

**Comment by lapoigne** [comment]
More information, I use a self signed certificate.
It could be rejected by default by RestSharp library ?

**Comment by mregni** [comment]
At this moment there is no option to enable more the INFO logging (there is no extra logging implemented anyway for the moment).

I have to test it myself if RestSharp blocks self-signed certs by default that could be the issue. The wss is for the socket connection (not really neede because the user statistics are broken) but there should be a PING log if you run the wizard. I'll create a nightly so you can test it with some more logging.

**Comment by lapoigne** [comment]
Just tested today with a let's encrypt certificate and all is OK.
So I confirm EmbyStat reject self signed certificates by default.

**Comment by mregni** [comment]
Oke, thanks for testing! I will see if I can configure RestSharp so that it accepts self-signed certificates.

**Comment by mregni** [comment]
@lapoigne, can you check if it works now in beta.18?

**Comment by lapoigne** [comment]
It's OK with the last beta.
Great job.
