### ISSUE TITLE
Linux Crazy CPU Usage

### ISSUE THREAD

**Issue by shenniko** [mregni/EmbyStat#1050]
# Bug report

**Describe the bug**
Embystats causes some crazy CPU usage on my Linux Server. Ending the Service stops this.
My server is re-boot every night at 3am, so its not like its been running for days..

**Screenshots**
Embystats Running
![embystat1](https://user-images.githubusercontent.com/30448631/72107622-9aae2080-3329-11ea-9841-389f1501873c.png)
Embystat Service ended
![embystat2](https://user-images.githubusercontent.com/30448631/72107631-9e41a780-3329-11ea-8d38-fe9cb89739c1.png)

**System (please complete the following information):**
System Info:
Linux 5.0.0-32-generic x86_64
Distributor ID: Ubuntu
Description: Ubuntu 19.04
Release: 19.04
Codename: disco

**Comment by mregni** [comment]
Wow, that is indeed some crazy stuff. And this is during a sync job or even on idle?

**Comment by shenniko** [comment]
Just when Idle.. It isnt like that when Embystat starts, just after a few hours... Maybe there is a specific job thats causing it? Though im not always logged onto the server to see whats going on.

**Comment by mregni** [comment]
Not really. Every 5 minutes I ping your Emby server to check if it's online. Other jobs are triggered daily. Still have to refactor a lot, I'll add it to my todo list to investigate what's happening here

**Comment by shenniko** [comment]
@mregni  Not sure if something has changed from version 12-14 (cant remember what version i raised this on) but doesnt seem to be happening any more..

Im running some script to output the CPU usage of embystats to see if anything pops up.. but hopefully this might be resolved..

**Comment by mregni** [comment]
Oke that's good news! I'm going to push beta.19 in an hour or 2. If anything looks strange to you let me know. 

Going to close this ticket but feel free to reopen or create a new one if needed! Thanks for testing.

**Comment by shad-lp** [comment]
I had the same issue, my NUC was making an outstanding noise, I found out EmbyStat was killing it.
Been running again for two days now, nothing wrong happened yet.
