### ISSUE TITLE
Overlapped text (dates/genres)

### ISSUE THREAD

**Issue by Dubwize** [mregni/EmbyStat#1062]
# Bug report

**Describe the bug**
The graph text is overlapped onto itself. This looks to be a bug for Brave browser only, Chrome functions as expected and all dates, etc are visible.

**To Reproduce**
Using Brave Browser
Access Emby Stats
Open Movies 
Scroll to graphs

**Expected behavior**
Expected to be 

**Screenshots**
I used the two easiest to recognizes graphs, but it is happening on all of them.

![image](https://user-images.githubusercontent.com/16105140/72634152-05fa8280-3928-11ea-8aef-0e2422bd97af.png)
![image](https://user-images.githubusercontent.com/16105140/72634159-0abf3680-3928-11ea-8ab8-8b07a25016b2.png)

**System (please complete the following information):**

Debian
Brave Browser 
(Chrome and Firefox were also tested and work correctly)
v0.2.0-beta.15

Not a high priority change of course, but Brave is gaining popularity.

**Comment by mregni** [comment]
I'll have to check Brave. Looks like the graph plugin I'm using is not working properly indeed.

**Comment by Dubwize** [comment]
Which is strange, because Brave is a fork of Chrome, so they are clearly doing something different in this regard.
Not a high use Browser at this point so not a huge issue all around.

Thanks for your work on this btw, very excited to see this project as it's something Emby never really had.

**Comment by Dubwize** [comment]
Just noticed the other side of the graphs are also not displaying correctly. In Brave only.
![image](https://user-images.githubusercontent.com/16105140/72744171-1191b780-3b7b-11ea-9ed5-c3efe3901dba.png)

**Comment by Dubwize** [comment]
This looks to be corrected in beta.25, counts and genre info shows correctly in Brave.
![image](https://user-images.githubusercontent.com/16105140/91190968-31193180-e6c2-11ea-8a95-80bf55ca3aac.png)

**Comment by mregni** [comment]
Thanks for the update! Going to close the issue then. Working with DevExtreme Graphs did decrease the bugs a lot :)
