### ISSUE TITLE
Where is TV info pulled from?

### ISSUE THREAD

**Issue by theflyingfool** [mregni/EmbyStat#1075]
# Bug report

**Describe the bug**
As I'm looking through my shows stats, attempting to find what shows I am missing episodes from I saw a couple I was fairly sure I had every episode to. Example: DuckTales, per thetvdb.com I have every episode and I have the missing episodes that are listed in a different season

**To Reproduce**

Not sure?

**Expected behavior**
Show 100% complete

**Screenshots**
![image](https://user-images.githubusercontent.com/2403507/73697556-da5bf400-46ac-11ea-97f1-90b85f318120.png)
![image](https://user-images.githubusercontent.com/2403507/73697598-f5c6ff00-46ac-11ea-8963-70fef1e111ea.png)
![image](https://user-images.githubusercontent.com/2403507/73697668-23ac4380-46ad-11ea-9d40-e62f9e1ae2c8.png)

**System (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version V0.2.0-beta.15

**Additional context**

**Comment by mregni** [comment]
That is some weird voodoo stuff 😄 I get the tv show info from TVDB. I'll have to check what's happening with that show. 

I'll keep you posted when my systems are back online and I had some time to look into this.

**Comment by theflyingfool** [comment]
Other shows with odd behavior: X-Men: The Animated Series
The TVDB:
![image](https://user-images.githubusercontent.com/2403507/73952427-e6260100-48cc-11ea-9ba7-53176429a5ab.png)
Emby Stat:
![image](https://user-images.githubusercontent.com/2403507/73952462-f1792c80-48cc-11ea-929d-7189ed4bd797.png)
(Season 1 only has 13 Episodes)
Harvey Birdman, Attorney at Law
![image](https://user-images.githubusercontent.com/2403507/73952622-300ee700-48cd-11ea-9072-0e6e967d100f.png)

![image](https://user-images.githubusercontent.com/2403507/73952599-28e7d900-48cd-11ea-9854-f18e0d5c6df5.png)

I have a few more that I believe are coming in with this weird voodoo, but these 3 are the only ones I'm sure of.

**Comment by Happy2Play** [comment]
> That is some weird voodoo stuff 😄 I get the tv show info from TVDB. I'll have to check what's happening with that show.
> 
> I'll keep you posted when my systems are back online and I had some time to look into this.

Wasn't it mentioned somewhere you are using DVD order instead of Official/Aired?

But with series having multiple Order options, you will have to integrate a per series Order option, since you are doing your own querying.

**Comment by theflyingfool** [comment]
I use the official/aired order for everything.

As far as my my own querying, only did it because emby stat was showing me info that didn't match what I believed I had for files.

Hopefully that answers what your asking.

**Comment by mregni** [comment]
Yeah, currently I'm using the DVD order because I saw some shows on theTVDB that had season 1940 and 1950 instead of 1 and 2. I do have to switch it back and find another solution for those strange shows 😄

**Comment by theflyingfool** [comment]
I did dig a little deeper into the problem and it does seem to be related to DVD order. I looked at the shows showing stuff missing, and the episodes I'm missing are in the DVD order.

Without having dug into how EmbyStat works, it seems like a solution could be a toggle for which order to use, possibly global, possibly per show

**Comment by mregni** [comment]
I will create a system that will first use the TVDB order (like before) and if I find a very strange season name (1950, 1940, ...) I can switch to DVD order. Let's see how that works out in the next beta.

**Comment by theflyingfool** [comment]
Looks good w/ beta.17
