### ISSUE TITLE
Question re: zip release structural change

### ISSUE THREAD

**Issue by aptalca** [mregni/EmbyStat#1147]
# Question
The zip releases for beta 17 contain a top level folder that is arch specific (ie. `ubuntu-x64`). Is this intentional or a bug with the ci/cd?

Thanks

**Comment by mregni** [comment]
This is indeed a bug in de ci/cd and I'll try to fix it asap. Thanks for reporting!!!!

**Comment by mregni** [comment]
New package is published with correct zip structure :)
