### ISSUE TITLE
Question re: default app data location

### ISSUE THREAD

**Issue by aptalca** [mregni/EmbyStat#1150]
# Question

I see that the help text lists various locations for data, config, log, etc. But what is the default value for those?

In the previous version, all data would default to the user's home folder. But now I don't know where the data ends up.

The reason I'm asking is because when I updated to the latest beta with the linuxserver docker, I get the wizard again so I'm guessing it is looking in a different place for my data.

Thanks

PS. Also, can one set all those folders to the same folder or should they be distinct locations?

**Comment by aptalca** [comment]
It seems I had a brain fart. The default location is the config folder in the app folder. I forgot that I symlink that to a different folder. I gotta chase that down.

**Comment by aptalca** [comment]
Ok, I see the problem now. In the previous version, all three (config, data and logs) resided under the config folder in the app folder. But in the latest beta, logs and data got moved to their own folders in the main app folder. So this effectively breaks all docker installs, both linuxserver and yours (I believe) since only the config folder was persistent. Just a heads up.

**Comment by aptalca** [comment]
I'm gonna go ahead and fix the linuxserver one. By the way, do you have a donation link? We just started promoting upstream donation links on our GitHub pages (sponsor buttons) as well as our container logs. If you do, I'll add that on as well.

**Comment by mregni** [comment]
Ow yeah, I mentioned this on the Emby forum. This is indeed a breaking update and should nog be updated. Sorry about that! I'm still working on getting some kind of stable environment so breaking updates will happen (hopefully not often anymore).

I created a donation link https://ko-fi.com/embystat, thanks for adding it to the sponsor button!

**Comment by mregni** [comment]
Is it a simple fix to move the config file locations? Sorry I didn't mention the breaking change!

**Comment by aptalca** [comment]
No worries, it's still beta so it's expected (plus it takes only a minute to set it up from scratch as it retrieves all info from emby anyway).

We fixed it by passing these arguments when starting it: https://github.com/linuxserver/docker-embystat/blob/master/root/etc/services.d/embystat/run#L7

**Comment by mregni** [comment]
Nice fix :) 
I'm also adding a --log-level argument that can be set to 1 (default 2, info) if debug info is needed. Just to let you know, don't know if you can use it in the docker setup really. Later I will add an option in the settings page to change the log level so a restart is no longer needed.

**Comment by aptalca** [comment]
Thanks. We usually leave the log level as default. If it's going to be adjustable via gui in the future, that would be perfect.

I went ahead and put the donation info so it is displayed both in the sponsor button on github, and the container logs:
```
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
EmbyStat: https://ko-fi.com/embystat

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
```

closing this now
