### ISSUE TITLE
failed to perform media sync task the second and subsequent times

### ISSUE THREAD

**Issue by saeddd** [mregni/EmbyStat#1169]
[2020-04-15 (2).log](https://github.com/mregni/EmbyStat/files/4480917/2020-04-15.2.log)
# Bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

- OS: [e.g. Windows, Ubuntu]

**Additional context**

**Comment by mregni** [comment]
Duplicate of #1156, this should be fixed normally in the new beta.19 release. 
If not, feel free to comment it that issue. Closing this one for now.
