### ISSUE TITLE
Majority of TV shows status is being reported as null

### ISSUE THREAD

**Issue by Dubwize** [mregni/EmbyStat#1203]
# Bug report

**Describe the bug**
Majority of TV shows status is being reported as null (see image),  this may be because of bad meta data somewhere as some do show correctly.   

**To Reproduce**

1. Go to Shows
2. Scroll down till you see the graph (see image)

**Expected behavior**
All shows should be either Ended, or Ongoing

**Screenshots**
![image](https://user-images.githubusercontent.com/16105140/81301137-ab0ba900-9046-11ea-9771-d672d79d808f.png)

**System (please complete the following information):**
OS: Debian 10
Browser: Brave, Chrome, Firefox
Version: v0.2.0-beta.18

**Comment by danshilm** [comment]
Just checked and the shows in the database don't have any values for their state, which suggests it might be doing something weird when getting info from the TvDb. However, it seems like the shows also have incorrect values for their state in the shows overview tab.

**Comment by mregni** [comment]
That is strange indeed. I'll check if something changed on the API. Maybe that I'm not receiving the state correctly anymore.

**Comment by mregni** [comment]
@danshilm, do you still have this issue in the beta.23? I did some rework in the show converter so this might be solved already

**Comment by danshilm** [comment]
Indeed fixed in beta.23. Thanks @mregni.

**Comment by mregni** [comment]
Thanks for the feedback, going to close the issue then for now.
