### ISSUE TITLE
Error with Series and Movies on JellyFin

### ISSUE THREAD

**Issue by angeltonio** [mregni/EmbyStat#1218]
When I put de API for Jellyfin works fine the list of ussers, and extensions, but the movies and series give me a error logs

15:31:42 14-05-20 MEDIASYNC-JOB => 0 movies found in parent with id 4230a6c21b952a1364bcdbe51a769351. Propably means something is wrong with the HTTP call.
15:31:42 14-05-20 MEDIASYNC-JOB => Lets start processing show
15:31:42 14-05-20 MEDIASYNC-JOB => Logging in on the Tvdb API.
15:32:03 14-05-20 MEDIASYNC-JOB => Job failed, check logs for more info.

2020-05-14 14:45:16.1227 [WARN] MEDIASYNC-JOB	0 movies found in parent with id ed2a25286c558a96e1424971742ca250. Propably means something is wrong with the HTTP call. 
2020-05-14 14:45:16.1326 [WARN] MEDIASYNC-JOB	0 movies found in parent with id 4230a6c21b952a1364bcdbe51a769351. Propably means something is wrong with the HTTP call.

**Comment by peioe** [comment]
I'm seeing the same. Not sure if this is related, but in "Server" in the left menu, default ports (8096, I'm using a reverse proxy and https is on port 443) are listed instead of the one I entered in the settings.

**Comment by Alcatraz077** [comment]
Same here as well, just installed it via Docker, setup to Jellyfin via the wizard with an API key. It gives me similar errors. Log attached.

Edit: I'm on EmbyStat v0.2.0-beta.20, Jellyfin version 10.5.5

[2020-05-22.log](https://github.com/mregni/EmbyStat/files/4670350/2020-05-22.log)

**Comment by Nosirus** [comment]
no news ?

**Comment by ghost** [comment]
I looked through some of the code and it seems like the jellyfin API requires a admin userid for calls to get any movie or show. I can try and look into a way to fix that without disturbing the emby users.

**Comment by Protektor-Desura** [comment]
I get the same error. It won't load any data from Jellyfin.

**Comment by Protektor-Desura** [comment]
I'm still seeing this with lastest version of Embystat on Jellyfin. It will not complete the "Media synchronisation" job.
EmbyStat version: 0.2.0-beta.20

I will say all other jobs work, "Small sync with Emby", "Database cleanup", "Check Emby connection". Note I am not running Emby but instead running Jellyfin.

**Comment by peioe** [comment]
The latest release is from May 19th, there's no point bumping this issue every week.

**Comment by mregni** [comment]
Hey guys, sorry for not getting back sooner. Been busy with the UI at the moment. 

There is a difference between Emby and Jellyfin and that is that some API calls need an admin user id for authentication on Jellyfin. That's why in the last step all Jellyfin setups need to choose an admin user.

But the problem itself in in the Tvdbclient, seems like the login is failing. I'll try to fix this in the next release. To bad I didn't add any debug logging to that part yet.

**Comment by mregni** [comment]
This should be fixed with beta.23, if not feel free to reopen this issue or create a new one.

**Comment by Ishannaik** [comment]
Having the same issue just installed EmbyStat with docker, everything works/all libraries are loaded but media sync shows the same error on jellyfin ubuntu 10.6.4

**Comment by SigHunter** [comment]
> 
> 
> Having the same issue just installed EmbyStat with docker, everything works/all libraries are loaded but media sync shows the same error on jellyfin ubuntu 10.6.4

I have the same problem as Ishannaik. Not possible to get EmbyStat working with Jellyfin at the moment. Running JF 10.7.0-rc2. I'm also using docker for embystat. I tried uping/embystat:nightly which currently is 0.2.1-dev.1373 aswell as ghcr.io/linuxserver/embystat
Logs: https://pastebin.com/Sc6YCUdd


edit: could also not get it working with EmbyStat-win10-x64-v0.2.0-beta.24

**Comment by Ishannaik** [comment]
> > Having the same issue just installed EmbyStat with docker, everything works/all libraries are loaded but media sync shows the same error on jellyfin ubuntu 10.6.4
> 
> I have the same problem as Ishannaik. Not possible to get EmbyStat working with Jellyfin at the moment. Running JF 10.7.0-rc2. I'm also using docker for embystat. I tried uping/embystat:nightly which currently is 0.2.1-dev.1373 aswell as ghcr.io/linuxserver/embystat
> Logs: https://pastebin.com/Sc6YCUdd
> 
> edit: could also not get it working with EmbyStat-win10-x64-v0.2.0-beta.24

I've heard the tool is broken for jellyfin currently and the dev is on vacation
