### ISSUE TITLE
White Page in Browser

### ISSUE THREAD

**Issue by MaDTaZ** [mregni/EmbyStat#1230]
Hello all

I am getting this error in the logs.
Job not running because wizard is not finished 

And 
Just a white page when I go to 6555. any ideas?

Should of mentioned
using beta emby and also running under linux native not docker

**Comment by mregni** [comment]
Did you see any errors in your browser console?
Also, you can try to go to http://<your-ip>:6555/wizard to start the wizard. Hope that helps!

I'm rewrite the whole UI for the moment so if it's not working just wait for the next beta with the new ui

**Comment by MaDTaZ** [comment]
Thank no that didnt work either but I will wait for the next beta and give it a try.  Thanks
