### ISSUE TITLE
Trying to download a log file results in "Unhandled backend exception"

### ISSUE THREAD

**Issue by n00b42** [mregni/EmbyStat#1294]
Trying to download a log file results in "Unhandled backend exception"
(Latest docker image)

**Comment by n00b42** [comment]
I temporaryly enabled Rollbar if that shows up someting.

**Comment by mregni** [comment]
Thanks, it did show up in Rollbar now. Seems like the path to the log files can't be found:
`System.IO.FileNotFoundException: Could not find file '/app/Logs/2020-08-08'. `

Is there a way you can verify this path and check where the log files really are? (a bit difficult if you are running in docker). I'm going to try to run the Ubuntu package in a VM later today and see if the file can't be found there as well.

**Comment by n00b42** [comment]
root@uping-embystat-x64:/app/Logs# ls                                                                                                                                                                                                                                                       
2020-08-08.log  2020-08-09.log

**Comment by n00b42** [comment]
seems the file is there, but has a suffix and the exception does not mentio the log suffix?

**Comment by n00b42** [comment]
The network monitor shows the following entry:

`http://192.168.0.200:8099/api/log/download/2020-08-09?anonymous=false`

![image](https://i.imgur.com/XVuSVyb.png)


**However if I modify the request to:**
`http://192.168.0.200:8099/api/log/download/2020-08-09.log?anonymous=false`
Then, I can download the log file!!

**Comment by mregni** [comment]
Oke, that means I'm missing the file extension somewhere! I will add the .log prefix again because I'm not sending it to the frontend.

**Comment by n00b42** [comment]
Updated my docker image today.
0.2.1-dev.1294

Log download seems to work.
