### ISSUE TITLE
Settings/Movies: Layout issue?

### ISSUE THREAD

**Issue by n00b42** [mregni/EmbyStat#1298]
Hi, I am not sure if thats the intended layout or if there are some issues, but thats how my settings/movies page looks:
![image](https://i.imgur.com/KaHVoqH.png)

(I censored one library name as it is personalized)

Btw. is "settings/libraries" or something similar not a more suitable menu entry.

Thanks for your work :)

**Comment by mregni** [comment]
settings/libraries should be good but the problem is that there is difference between show and movie settings. (Show pages are hidden for the moment in EmbyStat). So Maybe "settings/movie libraries" might be better.

As for the pictures, it should show the library pictures from your Jellyfin server. Going to test it on my own jellyfin test server to see what's happening.

**Comment by mregni** [comment]
@n00b42, can you supply me with the image URL that can't be loaded? You can find it in your Developers Tools in the network tab (probably). It will show up as a 404 request. 

I can display the library images correctly but I'm still testing it on a normal install (windows install, no docker). Image URL is http://xxx.xxx.xxx.Xxx:8098/jellyfin/emby/Items/e7699520467fd2392dc7a238a94300ce/Images/Primary?maxHeight=212&maxWidth=377&tag=c922a6f4b05e70e503a8d687a1aa2007&quality=90

**Comment by n00b42** [comment]
"http://172.17.0.1:8096/emby/Items/cc01444b416777d3fa55d5f13da1ce58/Images/Primary?maxHeight=212&maxWidth=377&tag=9738de1fe1b0b26b81d06c48222dd2d9&quality=90"

Oh, I think I found the issue and maybe thats the answer to the other issues as well:
Docker setup a network bridge (own IP range 172.17.0.1 instead of my home network 192.168.0.1), EmbyStat is able to "find" my Emby Server which runs on the same machine on 172.17.0.1:8096 which uses the bridged interface, my browser however does not know about that network bridge...

I am testing some stuff....

**Comment by mregni** [comment]
Thanks for the update! I'm also going to update the docker containers to use dotnet CORE 3.1 and add some volumes for data dirs and stuff. My experience with creating docker files is limited so I'll do my best to check it out :)

**Comment by n00b42** [comment]
Ok, created another docker instance and set the server url to 192.168.0.123:8096 and now the images show up fine.

![image](https://i.imgur.com/QUZ5o7c.png)

**Comment by n00b42** [comment]
So, the issue is that docker (on my synology) set up a network bridge interface which is of course only known to that server, and therefore the links do not work outside (eg. in the browser).

**Comment by n00b42** [comment]
Although, instead of using the IP provided during setup, it seems EmbyStat already knows about the "actual" IPs (both LAN as well as WAN)

![image](https://i.imgur.com/36XxNLz.png)

Are there any drawbacks of using this IP(s) instead of the one provided during install?
Or could we query that IP during setup already (and drop the bridge IP if connection is possible?

**Comment by mregni** [comment]
So If I'm correct you supply the WAN URL while performing wizard but now you want EmbyStat to use the LAN URL? Maybe a solution would be in the wizard the user needs to pick if EmbyStat needs to use WAN or LAN URL. Because always using LAN would be bad as well for users needing WAN support.

Would that fix your problem as well if you could pick LAN URL in the wizard flow?

**Comment by mregni** [comment]
@n00b42, are you using a Jellyfin or Emby server? I'm getting confused because when I try to connect to my Jellyfin test server I'm getting the strange images as well because the image URL seems to be wrong.

**Comment by mregni** [comment]
Going to create a nightly build for this fix. Can you test it? I'll let you know when the nightly docker container is released

**Comment by mregni** [comment]
@n00b42, nightly docker should be deployed in 30 minutes max. Let me know if the images load correctly for you.

**Comment by n00b42** [comment]
> 
> 
> So If I'm correct you supply the WAN URL while performing wizard but now you want EmbyStat to use the LAN URL? Maybe a solution would be in the wizard the user needs to pick if EmbyStat needs to use WAN or LAN URL. Because always using LAN would be bad as well for users needing WAN support.
> 
> Would that fix your problem as well if you could pick LAN URL in the wizard flow?

No, in my first install I used the automatically detected server (which used an IP address that is only a bridge network (a virtual network between docker client and docker server), as the docker server runs on the same machine as the Emby server.
This IP is neither LAN nor WAN, its more or less virtual (internal) LAN.

In a second attempt I reinstalled and did not use the automatically detected server but supplied the LAN address myself.

To clear things up: I have a Synology server (or more specifically a Xpenology) that runs **Emby**, but also has a docker system which I use to run EmbyStat.
This means both Emby as well as EmbyStat share the same device.
Now Docker could either use a virtual network as I did (this means the IP of EmbyStat is the same as the Emby), or expose it as a seperate device (in that case EmbyStat would get its own address, which I did not want)

**Comment by n00b42** [comment]
> 
> 
> @n00b42, nightly docker should be deployed in 30 minutes max. Let me know if the images load correctly for you.

As mentioned before and as it can be seen in the screenshots: After I manually set the LAN address during setup, the images worked.

**Comment by mregni** [comment]
Thanks for the info! That means that I do need to make a WAN/LAN address picker in the wizard

**Comment by mregni** [comment]
Added dropdown and fixed another issue with base URL's. If you want you can give the nightly docker container for a test run.

**Comment by n00b42** [comment]
Where did you add the dropdown?

![image](https://i.imgur.com/72OHHjy.png)

nightly-linux-x64 / 0.2.1-dev.1268

**Comment by mregni** [comment]
It's later on in the wizard. Here you can just give any connection you want that works from EmbyStat backend to Emby. When the connection is successful you will see a dropdown in the next step where you can select if you want to use the LAN or WAN connection (or current connection if it's different from LAN or WAN address configured on Emby)

**Comment by n00b42** [comment]
Should it be in the next step?

![image](https://i.imgur.com/TI1UQrG.png)

Cant find it in the other steps as well.

**Comment by mregni** [comment]
mmm strange. It should look like this instead 
![image](https://user-images.githubusercontent.com/22617019/89911340-99134680-dbf1-11ea-86bf-12159d8c3403.png)

Version number in menu bar
![image](https://user-images.githubusercontent.com/22617019/89911529-d8419780-dbf1-11ea-8d5e-3a10a50e49d7.png)

**Comment by n00b42** [comment]
Updated docker image today.
0.2.1-dev.1294
now the selection menu is visible.

**Comment by mregni** [comment]
Thanks for updating the issue!
