### ISSUE TITLE
Links to content on Jellyfin server broken

### ISSUE THREAD

**Issue by gerben838665** [mregni/EmbyStat#1335]
**Describe the bug**
When opening a link to a movie/show on Jellyfin it results in an error page.

**To Reproduce**
1. Go to the general page of Movies or Shows.
2. Click on on the titel name of a movie or show.

**Expected behaviour**
Opens the Jellyfin server page of the movie or show.

**System**
- OS: Unraid
- Browser: Edge Chromium
- EmbyStat version: 0.2.0-beta.23
- Media server type: Jellyfin

**Additional context:**
EmbyStat seems to open the wrong link might be because of a difference between emby and jellyfin.

Example
Link that EmbyStat tries to open:
https://[serverdomain]/web/index.html#!/item?id=fe125f45c4b27371c7847f3215fb0b13&serverId=5cc5d6f090da4952bc42ccb4d68b640f

Actual link when opening same content directly on the Jellyfin server:
https://[serverdomain]/web/index.html#!/details?id=fe125f45c4b27371c7847f3215fb0b13&serverId=5cc5d6f090da4952bc42ccb4d68b640f

Problem seems to be that EmbyStat uses item instead of details in links for content on a Jellyfin server.

**Comment by mregni** [comment]
Sorry, I was still running an older version of Jellyfin so that's why the links are wrong. I'm updating them asap

**Comment by mregni** [comment]
This issue is fixed in beta.24. Feel free to reopen if the issue still persists.
