### ISSUE TITLE
Shows not able to sync

### ISSUE THREAD

**Issue by gundamboyzack** [mregni/EmbyStat#1337]
# Bug report

**Describe the bug**
Media sync fails when starting to sync shows

**To Reproduce**
Run a media sync

**Expected behavior**
Media sync completes

**Screenshots**

**System (please complete the following information):**

- OS: Debian 10.4 x64
- Browser: Chrome
- Version: 0.2.0-beta.23
- Media server type: Emby

**Additional context**
EmbyStat is a new instance/fresh install for beta 23.  Also tried generating my own TVDB API key to verify its not a API key issue as the task fails after "MEDIA-SYNC - Logging in on the Tvdb API." step is logged, but the same issue persists.  Log file is attached.

[2020-08-22.log](https://github.com/mregni/EmbyStat/files/5112285/2020-08-22.log)

**Comment by mregni** [comment]
Thanks for logging your bug!

Can you please rerun EmbyStat with the --log-level=1 flag and send me the log file? It will output a lot more data so I'm able to trace the incorrect mapping.

**Comment by gundamboyzack** [comment]
Attached.

[2020-08-23.log](https://github.com/mregni/EmbyStat/files/5114806/2020-08-23.log)

**Comment by mregni** [comment]
This issue is fixed in beta.24. Feel free to reopen if the issue still persists.
