### ISSUE TITLE
Alternate Language Movie names in Table View.

### ISSUE THREAD

**Issue by Dubwize** [mregni/EmbyStat#1341]
# Bug report

**Describe the bug**
Movie names are not pulling English titles when they are Japanese.

**To Reproduce**
After the movies are imported;
Go to Movies -> Tables

**Expected behavior**
Name should be populated the same as they are in Emby, even if there are various names available.

**Screenshots**
Here are two movies listed in the tables display of EmbyStat.
![image](https://user-images.githubusercontent.com/16105140/91187745-82bfbd00-e6be-11ea-876b-9a8b1d6138e8.png)

Here is the same movies from Emby
![image](https://user-images.githubusercontent.com/16105140/91187894-abe04d80-e6be-11ea-9ce5-916ce7f7dc61.png)
![image](https://user-images.githubusercontent.com/16105140/91187937-b995d300-e6be-11ea-92ff-dfff1bc1857f.png)

Battle Royal's info on TheMovieDB 
![image](https://user-images.githubusercontent.com/16105140/91188391-3e80ec80-e6bf-11ea-8700-b40a16f5961f.png)

**System (please complete the following information):**
- OS: Debian
- Browser: Brave
- Version beta.25
- Media server type: Emby

**Additional context**
I would think that the metadata scrape should either populate whats already available from Emby, or if it's doing a new scrape from TVDB or TheMovieDB, then it should include your language selection when determining how/what to display as the title.

Couple more as reference:
![image](https://user-images.githubusercontent.com/16105140/91188691-97e91b80-e6bf-11ea-958e-bb1bf7355ceb.png)
![image](https://user-images.githubusercontent.com/16105140/91188792-b222f980-e6bf-11ea-8fda-c9acd99f6c2d.png)

**Comment by Dubwize** [comment]
As a side note.  Nice work on beta.25.  Very nice indeed.

**Comment by mregni** [comment]
Hi @Dubwize, thanks for the bug log. I was on holiday so I just now saw your issue. 

It is strange indeed that the Japanese titles are shown because I'm mapping the Emby data directly into EmbyStat. I did see that I'm using the OriginalTitle property, maybe Name or even SortName would be better indeed.

**Comment by Dubwize** [comment]
No worries man. Gotta get out and unplug sometimes.

I included that "Original Name" image because I assumed that was the value you were pulling. Also, and i'm not Emby variable guru, but i thought SortName was a user populated field, used to force Emby to override the title with what you have entered.

Thanks, and again,  keep up the great work, this new version is amazing.

**Comment by Dubwize** [comment]
Thought I would drop this here.   Looks like I was right about SortName.  It's user defined.    I would suggest using SortName first, and if that field = null, then use Title.

![image](https://user-images.githubusercontent.com/16105140/91673493-5e227580-eb02-11ea-8c93-863e3fa33938.png)

**Comment by Happy2Play** [comment]
> Thought I would drop this here. Looks like I was right about SortName. It's user defined. I would suggest using SortName first, and if that field = null, then use Title.
> 
> ![image](https://user-images.githubusercontent.com/16105140/91673493-5e227580-eb02-11ea-8c93-863e3fa33938.png)

Technically that field is blank in the UI but not the database. At least in Emby

![DB](https://user-images.githubusercontent.com/10268557/91680677-db4ceb00-eb00-11ea-8ffd-69281c7b2e5e.jpg)

**Comment by mregni** [comment]
Yeah, I'm also always receiving a sort name when I fetch the data from Emby. Displaying the SortName is a bad idea because this can happen
![image](https://user-images.githubusercontent.com/22617019/91689163-d2413580-eb63-11ea-9941-b13b51eeb147.png)

So will try to display the Name but sorting the name column needs to be done on SortName. Sounds like a plan?

**Comment by Dubwize** [comment]
> Yeah, I'm also always receiving a sort name when I fetch the data from Emby. Displaying the SortName is a bad idea because this can happen
> ![image](https://user-images.githubusercontent.com/22617019/91689163-d2413580-eb63-11ea-9941-b13b51eeb147.png)
> 
> So will try to display the Name but sorting the name column needs to be done on SortName. Sounds like a plan?

Sounds good to me.
....  and now that I know emby is storing everything in a sqlite db,  I'll be able to dig up more info for you, in advance, next time.

**Comment by mregni** [comment]
@Dubwize, can you check the new nightly build (0.2.1-dev.1365) to see if your problem is fixed? Nightlies are only available in Docker containers. Let me know if you need a Windows artifact.

**Comment by Dubwize** [comment]
I use a linux 'package' I can spin up a docker though and give it a test in a bit.

**Comment by Dubwize** [comment]
Small spelling mistake in that nightly.   might be in the main build also.  "Synchronization"

![image](https://user-images.githubusercontent.com/16105140/91861625-0c313b00-ec3b-11ea-91d7-62a1d506a046.png)


Unfortunately I can not get the docker nightly to do a media sync.  The issue is, it doesn't do name resolution correctly, so can't get out to TheTVdb.  To note, I run my dockers on a macvlan network.

docker create \
--name=Embystat \
--net="docker_vlan20" \
--ip="10.10.20.145" \
--dns="10.10.20.1" \
-p 6555:6555 \
-v /volume1/docker/embystat:/app/config \
uping/embystat:nightly

... all other dockers have access outside the network without issues

Using apt update as an example.   You can see it fails DNS lookups from within the EmbyStat Docker
![image](https://user-images.githubusercontent.com/16105140/91864197-eeb1a080-ec3d-11ea-807d-663bf7de8e87.png)

This is probably an issue with embystat:latest also, but i haven't tried to deploy it.

**Comment by mregni** [comment]
@Dubwize, I'm not really familiar with how the DNS resolving should work inside docker and how I need to change my code to use the docker DNS settings. You don't need to try the 'embystat:latest' since it's not updated anyway. 

Can you give me a docker image example that does work on your system? I could have a look at their docker image file to see if I'm missing something.

edit: fixing the type as well, thanks!
