### ISSUE TITLE
inotify instance error

### ISSUE THREAD

**Issue by lukelytle** [mregni/EmbyStat#1393]
the configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.

Anytime I try to install the docker for embystat all I get is this error in the log over and over. Can not get it to load at all and cant find any documents on this issue. Any help would be greatly appreciated.

**Comment by Happy2Play** [comment]
Programs like this and Emby just use inotify they do not set the limit configured by your system.  You will have to change the value set by your system.
https://stackoverflow.com/questions/57220658/change-inotify-max-user-instances-limit-in-docker-container

**Comment by mregni** [comment]
I have no knowledge of this option or what it does. Can I add some stuff to the docker container to fix this issue for everyone?

**Comment by danshilm** [comment]
> 
> 
> I have no knowledge of this option or what it does. Can I add some stuff to the docker container to fix this issue for everyone?

This needs to be set on the host system outside of Docker, so unfortunately, no.

**Comment by mregni** [comment]
Then I'm going to close this issue for now.
