### ISSUE TITLE
Movie Table Filter drawer

### ISSUE THREAD

**Issue by Happy2Play** [mregni/EmbyStat#1399]
# Bug report

**Describe the bug**
Filter drawer requires scroll right to see options.  This appears to only be when not maximized or full screen window.

**To Reproduce**

Open Filter in Movies table, when not full screen or maximized window.

**Expected behavior**

Should not need to scroll right to see filter options.

**Screenshots**
![filter](https://user-images.githubusercontent.com/10268557/95928846-526bd500-0d77-11eb-8159-94db74d0454d.jpg)

**System (please complete the following information):**

- OS: Windows 10
- Browser Chrome/Edge
- Version 0.2.0. beta 24
- Media server type Emby

**Additional context**

**Comment by mregni** [comment]
Thanks for the bug! Seems like an ugly design issue to me. I do have to fix the filters anyway because I don't like how they are displayed now anyway.

**Comment by mregni** [comment]
I recreated the filters and removed the drawer completely (because it always felt very buggy to me). I'm closing this issue for now, if there are issues with the new filters you can always create a new issue.
