### ISSUE TITLE
Url update required for Emby Beta

### ISSUE THREAD

**Issue by Happy2Play** [mregni/EmbyStat#140]
Emby Beta issue - soon to be Stable release

**Describe the bug**
All urls/links need updated with /index.html#!/

https://emby.media/community/index.php?/topic/59971-34116-change-the-default-local-address-windows-server/?hl=index.html%23%26%2333%3B

**To Reproduce**
Click on any link/image

**Expected behavior**
Navigate to movie/tv/people itemdatail page

.

**Comment by mregni** [comment]
You mentioned it before already, I totally forgot about it!
Will update in a couple of hours and pus a new beta.

**Comment by Happy2Play** [comment]
URL links are still broken in Suspicious movies.

EmbyStat version: 0.1.0.24

**Comment by mregni** [comment]
I found that issue as well a few days ago. Thanks for the update.
On the new beta version this will be fixed. 

I do have some problems with mu unit tests because I updated to .NET CORE 2.1, so new beta release is but delayed.

**Comment by mregni** [comment]
This should be fixed a few versions back. If not feel free to post a new comment
