### ISSUE TITLE
password bug

### ISSUE THREAD

**Issue by fjruhl** [mregni/EmbyStat#1424]
# Bug report

**Describe the bug**
when embystat loads it requests an login name and password 

never respondes

*To Reproduce**

close window

go to docker and webui to open a new inter face

**Expected behavior**
same thing job.rest.falure

**Screenshots**

![emby stat 01](https://user-images.githubusercontent.com/16024335/99459954-eee84080-28fc-11eb-8eb4-1eb6b28361fe.JPG)
![emby stat 02](https://user-images.githubusercontent.com/16024335/99459955-ef80d700-28fc-11eb-80e1-0aa47645576f.JPG)
![emby stat 03](https://user-images.githubusercontent.com/16024335/99459956-ef80d700-28fc-11eb-9239-cf38758530dc.JPG)

Problem.

**System (please complete the following information):**

- OS: unraid
- Browser  chrome

 Version docker up to date
- Media server type  Emby

![emby stat 01](https://user-images.githubusercontent.com/16024335/99460382-c01e9a00-28fd-11eb-9f16-5e735082b147.JPG)
![emby stat 02](https://user-images.githubusercontent.com/16024335/99460384-c01e9a00-28fd-11eb-917a-d782276715ae.JPG)
![emby stat 03](https://user-images.githubusercontent.com/16024335/99460385-c01e9a00-28fd-11eb-980a-469318a98681.JPG)

Additional context**

**Comment by danshilm** [comment]
If you upgraded from when there was no Login implemented, you'd need to start over with the installation (delete everything in the config directory that you mounted).

**Comment by mregni** [comment]
Sorry for not responding sooner but indeed. If you upgraded from a version without login you will need to reinstall the server completely as danshilm mentioned. 

Going to close this issue for now, if you still have this problem after reinstall feel free te create a new issue.
