### ISSUE TITLE
uping/embystat docker image

### ISSUE THREAD

**Issue by spupuz** [mregni/EmbyStat#1428]
Uping/embystat docker image is stuck to 3 months ago is this normal?

**Comment by theflyingfool** [comment]
I'm fairly sure that there has been no new release since Sept 8, so that would make sense.

**Comment by spupuz** [comment]
so the project is dead?

**Comment by theflyingfool** [comment]
Honestly, no idea, but I hope not.

**Comment by mregni** [comment]
Hey guys, the project has been in some deep sleep modus but I'm getting ready to start working on it again asap. 
I just released beta.26 so feel free to update your containers (clean install is still preferred for the moment) and let me know what you think.

**Comment by mregni** [comment]
Just released beta.30 with some new UI stuff and user list (first steps into user statistics)
Feel free to test this. Going to close this issue for now.

If you find any bugs you may always create a new issue here.
