### ISSUE TITLE
Docker: Jellyfin Initial Configuration "new API key not working!"

### ISSUE THREAD

**Issue by mil1i** [mregni/EmbyStat#1514]
# Bug report

**Describe the bug**
A new docker container, trying to go through the initial configuration wizard fails to connect. Logs returns a response of:
```
2021-04-12 19:48:41.6411 [DEBUG] BASE-HTTP-CLIENT	Returned object cant be parsed to ServerInfoDto 
2021-04-12 19:48:41.6411 [DEBUG] BASE-HTTP-CLIENT	RAW content:  
2021-04-12 19:48:41.6411 [DEBUG] SERVER-API	new API key not working!
```

**To Reproduce**

1. Go to Jellyfin settings
2. Click on 'Advanced > API Keys'
3. Click the '+' symbol, create new API key
4. Copy API key into initial configuration wizard, select next

Attempted with http (8096), https (8920). These ports are open on the Jellyfin docker container. Both containers are running on the same host machine, and same docker network.

**Expected behavior**
Successful connection and completion of configuration to connect to Jellyfin.

**Screenshots**
![Screenshot from 2021-04-12 19-54-52](https://user-images.githubusercontent.com/8459426/114485371-0932fb80-9bc9-11eb-82d1-827df7564cb9.png)

**System (please complete the following information):**

- OS: Docker
- Browser: Firefox?
- Version: beta-linux-x64, nightly-linux-x64
- Jellyfin (10.7.1)

**Comment by mregni** [comment]
Hi @mil1i, I just released a new version that should fix this issue.
Can you check If this is still an issue for you or not?

**Comment by mil1i** [comment]
Oh boy. @mregni I am unable to at the moment. The computer I was running as a server died, and I haven't replaced it yet.

I did spinup my Jellyfin/Embystat docker-compose on my personal machine and it does appear to be working. So I do believe it is resolved!

Thank you.
