### ISSUE TITLE
run statistics for home videos

### ISSUE THREAD

**Issue by eat-my-keyboard** [mregni/EmbyStat#1520]
# Feature request

I have lots and lots of vacation-videos, completely tagged with "actors" (family and friends), tags (like "climbing", "diving", "mountain biking", etc...) ... and i would love to run statistics over these videos as well.

As one can imagine they are not categorized as "movies" (as they aren't and i won't bother tmdb with requests) ... they are a "Home Videos and Photos"-Library in emby. Can there please be an option to run statistiscs over these type of libraries? I'd love to have an **overview of the people and tags for them**. Right now they aren't even showing up in the statistics. (understandable, as they are neither movies, nor tv shows).

Thanks in advance for considering and answering!

**Comment by mregni** [comment]
Hi, this is a nice feature request! 
Currently home videos are not yet in scope of the project because I still have a massive scope to implement first to get a basic server running. What you can do is create a feature request here: https://embystat.featureupvote.com/ This way I can keep better track of everything.

Thanks for testing EmbyStat!

**Comment by eat-my-keyboard** [comment]
Hi mregni ... thank you for replying and considering. I'm glad you are considering the request. If i can do anything to support you further to implement that feature, please let me know.

For others who might read this: i will upvote this:

https://embystat.featureupvote.com/suggestions/110346/support-for-extra-libraries-such-as-music-photos-and-home-videos

because it sounds similar and comment and link on it to connect it to this feature request :)

Kind Regards eat-my-keybard :)

**Comment by mregni** [comment]
Thanks for sharing the feature request link! I'm going to close this issue for now but feel free to upvote this issue to get it higher in the ranking.
