### ISSUE TITLE
Users info page missing?

### ISSUE THREAD

**Issue by nonyhaha** [mregni/EmbyStat#1648]
# Bug report

**Describe the bug**
I am running version 0.2.0 b27. I know there used to be a section with info about the users, and now this section is missing, or is it gone from the project?

**To Reproduce**
Login to embystat after configuration. Should be a section in the main menu.

**System (please complete the following information):**

- OS: win server
- Browser chrome for windows and for android
- Version 0.2.0 b27
- Media server type Emby

**Comment by mregni** [comment]
I added a first version of the user pages again. Feel free to test beta.30
