### ISSUE TITLE
[Feature Request]: Check airdate for completion

### ISSUE THREAD

**Issue by player8472** [mregni/EmbyStat#1681]
![grafik](https://user-images.githubusercontent.com/7383656/147691405-685399b5-f323-4935-a6d2-7f59e926c1ad.png)

Like shown in the picture, the completion doesn't take into account if something actually aired yet.
I think it should, since it ruins the whole thing and makes working with the data harder.

**Comment by mregni** [comment]
Valid point, I added a filter so that unaired episodes are not in the list.
Currently preparing a new release, so stay tuned for the update.

**Comment by mregni** [comment]
This has been released in beta.30 Can you check if this problem is still there or fixed for you?
