### ISSUE TITLE
IP address got change through ISP from power outage

### ISSUE THREAD

**Issue by glbjr29** [mregni/EmbyStat#1733]
How can I change the server that I am using? I am using Docker through Unraid,

**Comment by mregni** [comment]
I just released beta.30 so might be a good idea to reinstall the application.
You can always update the server settings in the settings page.

**Comment by glbjr29** [comment]
Wouldn't allow me to change it is the reason I created the post. Will try to reinstall it.

Sent from Yahoo Mail on Android 
 
  On Tue, May 17, 2022 at 2:57 AM, Mikhaël ***@***.***> wrote:   


I just released beta.30 so might be a good idea to reinstall the application.
You can always update the server settings in the settings page.

**Comment by mregni** [comment]
If you still can't update the IP after going installing beta.30 let me know. Might be helpful if you could add some logging (debugging) if possible.
