### ISSUE TITLE
Selection of default indexer

### ISSUE THREAD

**Issue by Callio91** [mregni/EmbyStat#1834]
Hello,

I have been using EmbyStat for some time. I read in the previous requests that you had chosen TVMaze as the default indexer for series. This works in most cases except for series that can be split in "ARC" for example some anime. For my part I use the TVDB convention. Is it possible to allow users to choose their own preferred indexer? Without this, there are missing episodes that simply don't exist in the season ranking instead of the "ARC" ranking .

Besides that, it's a very nice tool, thanks to all of you for the work you provide.

**Comment by mregni** [comment]
Sounds like a good idea to have some indexer options. I picked TVMaze because TMDB did some strange stuff with specials, sadly.
Not sure yet how we can make the indexer work, some kind of list of indexer that the user can drag and drop in the correct order or even disable? Currently, I only have TMDB and TVMaze, since TVDB placed their API behind a paywall.

**Comment by mregni** [comment]
@Callio91, not sure if you mean to have an indexer priority list for each show/film, or should a global list be ok for you?

**Comment by Callio91** [comment]
Hello, bad news for TVDB, though TvMaze does the job for series, it's for anime that it sometimes fails. If other users report this concern, maybe there exist other indexers a little more oriented to this type of content. In any case, being able to choose a priority from a supported list should answer the need and would certainly be an interesting option. Adding it for each series/movie would probably be too constraining for you to manage and would require redesigning the interface etc...

**Comment by mregni** [comment]
Can you give me a good indexer for anime? Maybe I can see if Emby flags the show as anime and use a different indexer automatically. Still have to do some research for this but it's just an idea.
