### ISSUE TITLE
Implement EmbyStat authentication

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#217]
First figure out how we can use Bearer tokens without SSL (don't think it will work without SSL)
So if not, find another authentication system and implement it.

**Comment by ghost** [comment]
I'd recommend ldap authentication. Both emby and jellyfin have an ldap plugin. So EmbyStat can leverage the same ldap as emby/jellyfin.

**Comment by mregni** [comment]
Thanks for the idea! It would be nice to include LDAP auth as well. I create a new issue to track it.
