### ISSUE TITLE
Simplified Chinese translation

### ISSUE THREAD

**Issue by OUZYcn** [mregni/EmbyStat#416]
https://crowdin.com/project/embystat

How to add  Simplified Chinese language?

**Comment by mregni** [comment]
Nice you want to help translate the app!

I just added Simplified Chinese to the crowdin tool, you can find it here
https://crowdin.com/translate/embystat/39/en-zhcn

If it's not the correct language let me know. I will add the language support in the app on the next beta update soon.

**Comment by mregni** [comment]
@OUZYcn 

Can you give me the translation of "Simplified Chinese" in Simplified Chinese? So I know how to display it in the dropdown menus.

**Comment by OUZYcn** [comment]
Simplified Chinese = 简体中文

it should be translated all. please check.

**Comment by mregni** [comment]
Thanks for the fast response!

I see you translated 40% of the tags. This will be visible when the new beta is released

**Comment by OUZYcn** [comment]
> Thanks for the fast response!
> 
> I see you translated 40% of the tags. This will be visible when the new beta is released

Should be done already. But don't know why there is some words show not yet translate from page 3 of 5. However its already translated by me.

**Comment by mregni** [comment]
Mmm, I just checked. Page 1, 2 and half of page 3 or not yet translated. Maybe some translations did not get saved?

![image](https://user-images.githubusercontent.com/22617019/53174007-1192db80-35e9-11e9-981d-a22239a9dcae.png)
