### ISSUE TITLE
Users fail on small sync

### ISSUE THREAD

**Issue by cuzz1369** [mregni/EmbyStat#477]
# Bug report

**Describe the bug**

Small sync fails to finish, errors out on users

**To Reproduce**
Run a small sync
**Expected behavior**
The sync to finish without an error

**System (please complete the following information):**
Version: 4.0.1.0 - 0
Host OS: Linux
EmbyStat version: 0.1.0-beta.33 
Operating system: debian x64 9

**Additional context**

![image](https://user-images.githubusercontent.com/6439289/53678217-f7f93000-3c89-11e9-9501-5044dcef7ece.png)

Log
2019-03-02 06:19:13 [INF] Connecting to wss://my.server.com:443/embywebsocket?api_key=af8778e76f864dd8973165ff68d20035&deviceId=42f1045a-6075-486f-a324-a4a21f02ee9a
2019-03-02 06:19:13 [WRN] Web socket connection closed.

**Comment by mregni** [comment]
Hey, sorry I didn't see your bug report before!

Can you tell me there is a exception in your logs as well? Looks like downloading the devices is crashing at your server. I will look into it, probably some null objects

**Comment by mregni** [comment]
@all-contributors please add cuzz1369 for bug
