### ISSUE TITLE
Check if show is not watched by anyone

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#50]
It would be nice to quickly see all shows that are not watched by anyone instead of checking it per user.

**Comment by rTiGd2** [comment]
Oh this is almost exactly what I was going to ask for. It would be nice to see if something is in progress (TV) or has/has not been watched at all (both TV and Movie) as that'll help to decide when something needs removing for being terrible, or just all no longer viewed.

Perhaps this may also nicely link to play lists (as someone may have a movie/series in a playlist for them to get around to watching but hasn't had chance yet)?

**Comment by mregni** [comment]
I'm working on some ideas on how to implement this and how the UI should look like.
