### ISSUE TITLE
Emby password with special chars not accepted

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#619]
Login to Emby fails if user has a password with following chars in it: 

& " @ ; : ,

Seems to be an encoding problem. 

Emby forum post [here](https://emby.media/community/index.php?/topic/56640-developing-a-standalone-embystat-server/?p=726111)

**Comment by mregni** [comment]
Looks like the problem is back on the table when I moved to RestSharp NuGet package for HTTP request.
Probably need to delete the UrlEncoding call on username and password

**Comment by Happy2Play** [comment]
This did not happen in .12 and am able to update .12 to .13 without issue.

From a clean install of .13 the wizard fails at Emby user password with special characters.

**Comment by mregni** [comment]
Thanks for the feedback, it looks like I don't need to url encode the username and password anymore. The update from .12 to .13 worked because I'm not really saving the Emby password bt just asking for an authentication token. 
I'm working on setting up the API key implementation(#64) to make life a bit more simple for all of us :) Should be ready soon.

**Comment by Happy2Play** [comment]
You could require users to generate and apply a api key.

They would generate it via Dashboard-API keys in 4.3, Dashboard-Advanced-Security tab in 4.2.

**Comment by mregni** [comment]
Yes, I'm almost done. Just have to add some unit tests before merging :) Thanks for the tip!

**Comment by mregni** [comment]
This should be fixed because I removed the user login flow and implemented to Emby API key support. If this is still an issue feel free to reopen this issue.
