### ISSUE TITLE
Docker storage location

### ISSUE THREAD

**Issue by Thunderoux** [mregni/EmbyStat#691]
The ability to choose storage location for information within docker

**Comment by mregni** [comment]
You mean having the ability to create a volume for the EmbyStat database? You can already create a volume for the settings, just mount the /Settings path (if that doesn't work try the /app/Settings path as well)

The database itself is still in the root, but when I move to LiteDB in issue #720 you will be able to mount a path to the database as well.

**Comment by Fma965** [comment]
Wait so it's not currently possible to keep this persisitent accross reboots? since the DB can't be mapped in docker.

**Comment by mregni** [comment]
If you leave the container alive it will keep your db as well. But if you do a docker run on every boot it will create a new docker container with a new db. So make sure you keep using the same container after all reboots for the moment.

It will be fixed when I move to nosql

**Comment by NiklasOlofsson** [comment]
So, is this fixed? We need to be able to map the settings and database outside of the container.
