### ISSUE TITLE
Auto discovery defaults to https instead of http

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#809]
Apart from me not noticing that the wizard had https as default when it discovered my server, the setup went well. => https://emby.media/community/index.php?/topic/56640-developing-a-standalone-embystat-server/?p=765677

=> Probably because I switched http and https values and forgot to switch them in the wizard discovery flow

**Comment by Happy2Play** [comment]
Not sure if related to this change but double http:// now on discovery.
https://emby.media/community/index.php?/topic/56640-developing-a-standalone-embystat-server/?p=765918

**Comment by mregni** [comment]
Yes indeed, I created a new bug fixing this one. I'll patch it with the next 0.2.0 release build!

Thanks

**Comment by mregni** [comment]
Looks fixed to me, if not please reopen this issue.
