### ISSUE TITLE
Episode count or play time looks wrong

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#812]
Someone reported that his total playable episode time is completely of: https://emby.media/community/index.php?/topic/56640-developing-a-standalone-embystat-server/?p=766100 

=> 18673 episodes across 148 shows, but a total watchable time of 3d 13h 7m (an average of 16.4 sec per epp)

**Comment by mregni** [comment]
@all-contributors please add Darkassassin07 for bug and test

**Comment by mregni** [comment]
ASked darkassassin07 if the problem is still there: https://emby.media/community/index.php?/topic/56640-developing-a-standalone-embystat-server/?p=770291

**Comment by mregni** [comment]
It seems it's still there and I know why. Looks like the show runtime ticks is the default episode length not the sum of the show. So I need to do an extra calculation to get the proper runtime

**Comment by Darkassassin07** [comment]
Ah ok, good to hear you've worked out the issue. I was worried I might have some wierd issues with some of my unwatched content.

**Comment by Darkassassin07** [comment]
Hey, can we re-open this one?
This issue never went away for me. Im still seeing just over 3.5days of total runtime for over 19k tv episodes.
(running .10)

**Comment by mregni** [comment]
Seems issue is indeed not fixed, grrr
