### ISSUE TITLE
Support localization for date format

### ISSUE THREAD

**Issue by diedrichg** [mregni/EmbyStat#822]
# Feature request

**Describe the solution you'd like
It would be nice to support date format localization. Example:
25/12/2019
would be
12/25/2019 for some countries (USA)

**Describe alternatives you've considered
I can live with it as it is, just gotta retrain the brain but it would be nice to see it in the way a country displays their format.

**Comment by mregni** [comment]
Localization is the hell in software development and at the moment the dates are hardcoded indeed. I will have to check how to format them correctly in Angular. Normally there is!

**Comment by mregni** [comment]
i18next supports this, so normally this should work now if you select the correct language in the settings page. If it's still failing, feel free to reopen this issue
