### ISSUE TITLE
General grammar and spelling suggestions

### ISSUE THREAD

**Issue by diedrichg** [mregni/EmbyStat#823]
# Bug report
Please take these suggestions with a grain of salt, I am in no way a U.S. english laureate. The following are suggestions for correction

**Movies Page**

- [x] Youngest Premiered to Newest Premiered
- [x] Youngest Added to Latest Added or Recently Added

**Shows Page**

- [x] Youngest Added to Latest Added or Recently Added
- [x] You can drop the "show" at the bottom of the posters - we know we are on the Shows page. Therefore, "Highest rated show" would become "Highest Rated". Note the title capitalization (bug #821 )

**Settings Page**

- [x] Both the Movies and Shows tabs: In the checkbox lists, the "video's" should not have an apostrophe, it should be just "videos".
- [x] Also in these lists: "tv" should be capitalized "TV" - It's like CD or DVD

> "TV" is an initialism — an abbreviation in which we say the name of each letter. Although there are some exceptions, initialisms are usually written in upper case. This helps the reader understand that it is an initialism.

- Version: v0.2.0-beta.4

**Comment by mregni** [comment]
Thanks for the long list of spelling suggestions. I'm not a native English speaker (as you probably noticed) so suggestions are always welcome. 

If you find more just add them to this issue.

**Comment by mregni** [comment]
Updated the initial post to checkbox list
