### ISSUE TITLE
Media Sync Job not finishing for Series

### ISSUE THREAD

**Issue by PartTheSeas** [mregni/EmbyStat#847]
# Bug report

**Describe the bug**
Mediasync job not finishing for TV shows. It seems like there's an issue with the new TVDB and some of my shows on Emby. Please see screenshot and logs attached.

**Expected behavior**
It should finish the media syncing for TV shows, but won't and fire error messages. Please see logs

**Screenshots**
[2019-08-01.log](https://github.com/mregni/EmbyStat/files/3456244/2019-08-01.log)
![Mediasync Error](https://user-images.githubusercontent.com/38896845/62287137-8a7c4600-b459-11e9-9f0f-1b0dfcd1b2ba.PNG)

**System (please complete the following information):**

- OS: [Win 10
- Browser Chrome
- Version v0.2.0-beta8

**Comment by mregni** [comment]
Thanks for logging the bug. Can you attach your log file as well? It seems that the sync with TVDB is going fine (except for the 4 missing shows). I have the same problem with 3 other shows, still no idea why TVDB returns a 404 on them. 

It looks like your issue is in the calculation of the show statistics.

**Comment by PartTheSeas** [comment]
Hey mregni.

Thank you so much for chiming in. First off: I love what you do and you make my Emby experience even better with all of your efforts <3 Please note that I've already attached the logs (under the screenshots section), my bad.

If EmbyStat can't pick up these shows (and TVDB returns a 404) it's not a big deal, but in my specific scenario the media syncing job isn't finished for series after all (and opening the Series tab on EmbyStat replies with "Unhandled backend exception").

I just clean installed EmbyStat again and let another MediaSync job run. Maybe this will workout now. I'll report back after it finished 👍 

Thank you so much <3 Emby(Stat) is the best <3 :)

**Comment by PartTheSeas** [comment]
Nope. It still doesn't finish the media syncing job.

Please see the following logs

[2019-08-01.log](https://github.com/mregni/EmbyStat/files/3457976/2019-08-01.log)

**Comment by mregni** [comment]
Wow sorry, I missed the link. My bad!

Thanks for the kind words and for testing the application when it's still en beta. I'm trying to get the application stable so reports like this are more than welcome!

Looks like the statistics calculation fails because he tries to look up a person with the name "-" and Emby returns a status 500. I'll create a fix that will check so the name length > 2.

**Comment by PartTheSeas** [comment]
Wohooo! That sounds great! I know ETA questions are not welcome on any developing platform and you **don't need to answer it**, but how long do you think this needs? (No answer needed in this regard)

Other than that I really appreciate all of your efforts and I was so happy when beta v0.2.0 came out, as I was almost updating GitHub every day ever since beta v0.1.0, which didn't work at all for me due to the database lock issue :( I was so hyped when you released beta 0.2.0 and I saw all the statistics for my server now <3 It's just a bummer that it doesn't work now again *screaming and flipping tables* :D So take your time and if there's any way I can donate to you via, let's say PP, give me the link here hehe :)

**Comment by mregni** [comment]
Hahahaha, no problem man! Yeah the database locks were hell on earth, but using the LiteDB changed a LOT in a good way. ETA will be 1 hour probably, I'll see if there are some other quick wins before creating a new beta version.

**Comment by PartTheSeas** [comment]
You're one of a kind! Thank you so much, can't wait!

You know, I was a long term Plex enthusiast, coming back to Emby twice, after finally noticing that Emby fits my needs much better (and the needs of my users) and was always on the hunt for something similar like PlexPy (Tautulli), which rounds up the Media Server experience and your tool finally did that and I feel like this is a sick and huge improvement for Emby! Emby now finally beats its biggest competitor in all regards (personal opinion) and I'm sooo happy you fired EmbyStats to us! (Was a huge lover of your Emby plug in on my first Emby try as well :))

So thank you so much and put everything in the next release the other users might have had problems with as well! I love your work and you make the experience for many people much, much better, as I assume a little enthusiast is in all of the Plex and Emby users :) Big love <3!

**Comment by mregni** [comment]
Thanks man :D I'll do my best to get EmbyStat where PleyPy is already but it will take a lot of time before I get there. 

Can I ask why you favor Emby over Plex? I did try Plex ones but just liked Emby more because in the days it was open source and I loved it was written in C# as well.

**Comment by PartTheSeas** [comment]
It's mainly for 2 reasons. The first one being is, that all my users have a way better streaming experience than with Plex. Less buffering, nolagging, instant stream starts (Since Emby v4 that is) and also, that I have way less CPU weight with Emby. And the other one is, that I personally like the UI more and all the customizations you can do with Emby. It's just my personal preference. 

All of the reasons finally convinced me that Emby is much better for my needs (and for my users) :)

It's not a big deal man, if you need long time to eventually get where PlexPy is! What you do is great and also completely sufficient for my needs (atm)! I like the UI, the features and everything's very good with EmbyStat! The only thing I'd love is, if we'll get to an eventually stable build, meaning it works for longer than a couple of days over here haha :D But no biggie, thanks again for all of your efforts, you're doing great so far and you have +1 happy EmbyStat fanboy! =)

**Comment by mregni** [comment]
You can find the fix in the nightly builds in an hour or so! But feel free to wait until I can push the fix to beta.

I hope I will get a stable version soon as well. being able to keep it running for more then a couple of days should be possible soon :)

**Comment by PartTheSeas** [comment]
Hey Mregni!

Thank you so muc <3! Where do I find the nightly builds though? I'm not very familiar with Github and couldn't find it 🙈 Do you maybe have a link or something? 🙈

**Comment by PartTheSeas** [comment]
Oh boy, I'm sorry. It was merged into the latest beta (nightly) you meant, amirite? 🤣 Sorry, it's working perfectly regni! Great-fuck-a-doodl-y-awesome job! <3

**Comment by mregni** [comment]
I'm merging it now into the release/0.2 branch meaning there will be a new beta version available in a couple of hours. It takes some time to build and packages all the zip folders and docker conainers :)

THe nightly builds at the moment can only be found in the docker containers with tags 'nightly-win10-x64' and 'nightly-ubuntu-x64'

**Comment by PartTheSeas** [comment]
Hey Regni! Idk what happened then, but it worked today before you merged it somehow. Maybe Emby updated that actor with the name "-" in the meantime? Anyways, that's good news :) And thanks for the nightly hint 💯
