### ISSUE TITLE
Multiple qualities of a movie or tv show

### ISSUE THREAD

**Issue by diedrichg** [mregni/EmbyStat#852]
# Feature request

**Is your feature request related to a problem? Please describe.
We need to think of a way to present movies (or TV shows) that have multiple qualities. In v0.2.0-beta8 I'm seeing Ready Player One listed under Duplicate Movies because I have a 4K version and a 1080p version. Multiple versioning support was added to Emby three versions ago (not too long ago).

**Describe the solution you'd like
We need multiple version detection. This would then allow you to create a new statistic called "Multiple Version Movies". I don't think we should eliminate multiple version movies from the Duplicate Movies stat because what if someone forgot they had a version that they intended to delete - this would help them out to make that detection. 

.......but now that I think of it, what's the difference between Multiple Version Movies and Duplicate Movies? I guess none. So maybe we don't need a new stat. Maybe a different way of presenting multiple versioning? Maybe we don't need a change at all?

**Comment by mregni** [comment]
You are making some valid points here! I was thinking the same thing that I have no idea if a duplicate is only checked by IMDB id or also by quality, file size, ...

At the moment I will leave the check as is, but maybe I can create a page to view all duplicates and the EmbyStat user can then delete the duplicate when he finds the duplicate a non-issue (for example same movie but different resolution) and fix all other duplicates. Just a wild idea ofcourse.

**Comment by mregni** [comment]
I added a new checkbox in the settings page that will disable the duplicate movies table. So if wanted, you can remove the stat from your movies page since version beta.10 (I think :) )
