### ISSUE TITLE
Missing episode option enabled breaks media sync

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#865]
When the admin user has the "add missing episodes" option on Emby enabled it will break the total ep count and collected state. 

Fix => Add a check on sync to see if an ep has video stream or valid path

**Comment by Happy2Play** [comment]
Or exclude isVirtualItem.

**Comment by mregni** [comment]
Haaa thanks for the tip! I was looking for something like that :D

**Comment by mregni** [comment]
Seems like the IsVirtualItem is removed from the Emby BaseItemDto
![image](https://user-images.githubusercontent.com/22617019/62598274-29d18b00-b8e9-11e9-8392-ffbd4b4a97bf.png)

Have to find another solution for this bug

**Comment by mregni** [comment]
Contacted Luke, it should be LocationType != Virtual
