### ISSUE TITLE
Various authentication issues

### ISSUE THREAD

**Issue by diedrichg** [mregni/EmbyStat#879]
# Bug report

**Describe the bug**

- [x] TVDB 401 unauthorized
- [x] Can't find The Flash
- [x] Error while running job System.ArgumentOutOfRangeException

**To Reproduce**
See attached log
[2019-08-09.log](https://github.com/mregni/EmbyStat/files/3485606/2019-08-09.log)

**System (please complete the following information):**

- OS: Windows
- Browser: Firefox
- Version 0.2.0-beta9

**Comment by mregni** [comment]
Thanks for the log! I'll have a look later this weekend

**Comment by diedrichg** [comment]
- [x] HttpRequest options, Boolean sendFailureResponse
[2019-09-22.log](https://github.com/mregni/EmbyStat/files/3639381/2019-09-22.log)

**Comment by mregni** [comment]
I'm starting to work again on the project after a break. I'll have a look later on why you get a System.ArgumentOutOfRangeException!

As for the not found problem, that's because there is a wrong tvdb id on the database. It seems that tvdb changed there id's and the old ones are still in EmbyStat. I will need some kind of hard media sync option so users can force a full media scan instead of just an update.

**Comment by mregni** [comment]
@bluezog has the exact same problem. Authentication is done but next call returns a 401. No idea why. The System.ArgumentOutOfRangeException is happening when calculating the collected rate chart.

[2019-09-23.log](https://github.com/mregni/EmbyStat/files/3645508/2019-09-23.log)

**Comment by diedrichg** [comment]
I ran a clean installation of beta .12 and did not receive any errors! Still have the TVDB ID issue with "The Flash (2014) though.
[2019-10-01.log](https://github.com/mregni/EmbyStat/files/3676969/2019-10-01.log)

**Comment by mregni** [comment]
Can you check on your Emby server that the link to TVDB works from the media page itself? Because it looks like Emby is sending the wrong TVDB id then when you run your sync.

**Comment by diedrichg** [comment]
Okay, I'm 96.7% sure I checked the tvdb ID awhile back but I checked it again - directly pasting the ID from their website into the ID field in Emby. I then took a redundant step and did "Identify" within Emby and replaced all metadata. This seems to have cleared it all up, it was just user error. I believe you can close this issue as I am no longer seeing any of the reported issues! Good job, Reggi!

**Comment by mregni** [comment]
Thanks man, closing the issue :)
