### ISSUE TITLE
very long time media scanning

### ISSUE THREAD

**Issue by skidda666** [mregni/EmbyStat#935]
# Bug report

**Describe the bug**
Not to sure label this as a 'bug' per say, but it is taken a VERY long time to scan my media library. I do however have an extensive collection of about 20TB. However this media scan has stayed at 86.7% for over 4 days now without moving or going onto other scan queues.

**To Reproduce**
first time installation and media scan on full library caused issue.

**Expected behavior**
Was not expecting a 3-7 day media scan, or if it's even normal.

**Screenshots**

**System (please complete the following information):**

- OS: Windows Server 2016
- Browser Firefox (running within Organizr) also on it's own locahost tab
- Version 0.2.0 -beta 10

**Additional context**

**Comment by Happy2Play** [comment]
I just did 30TB of media and scan took 2 minute(s) and 25 second(s).  I would assume you will need to provide a log.

**Comment by mregni** [comment]
Hi @skidda666, This is indeed some strange behavior. Can you provide me with a log file so I can see if something strange is happening?

**Comment by skidda666** [comment]
i have three log files, one from the first time i installed it and then two
smaller ones, i'll send the first one seeing as it was when the initial
media scan took place

**Comment by skidda666** [comment]
I have run the media scan and went on this afternoon and was greeted with a
fail ping for emby server as well here is the log file as well
[image: embystaterror.JPG]

**Comment by mregni** [comment]
@skidda666, can you reply directly on the github website instead of over email? It seems that your log file or images or not displayed properly.

Did you setup your EmbyStat with Nginx perhaps? There are some know issues with that at the moment.
