### ISSUE TITLE
[FeatureReq] additional command line argument for --no-updates

### ISSUE THREAD

**Issue by aptalca** [mregni/EmbyStat#960]
# Feature request

Hi,

I'm one of the LinuxServer.io team members and am maintaining the newly published embystat image: https://hub.docker.com/r/linuxserver/embystat and https://github.com/linuxserver/docker-embystat
We version control our docker images on the hub via image tags, and prefer to disable in container updates. EmbyStat by default has updates enabled.

A command line argument such as `--no-updates` or `--disable-updates` to use when starting `EmbyStat`, which would disable in app updates would be very helpful in maintaining our versioning and would help with support requests.

I'm really liking EmbyStat by the way. Great job and keep up the good work.
Thanks

**Comment by mregni** [comment]
Hey, cool to see you guys picked up my project even if it's still in early beta :D 

I can create such an argument, no problem. You also want me to disable the update job itself and remove the "update" tab in the settings? That way the user can't update EmbyStat anymore from within the app. Or just disable the update by default but when the user runs the update job or enables the auto-update option it should be able to update.

**Comment by aptalca** [comment]
A couple of us team members just started using it and we like it quite a bit so far. Great job.

If it's not too much work, the option of totally disabling it would be great. We publish a new image whenever there is a new release (usually within an hour), so there is no reason to enable in container updates.

Just a heads up, once you go stable, we can branch off the prereleases and track them via a different docker image tag. For sonarr and some of the other *arrs we do `latest` tracking the stable releases and we have a variety of `develop`, `nightly` or `preview` tags for folks who want to track those prereleases.

**Comment by mregni** [comment]
Would be better indeed to disable it completely then. I'll have a look at how I can implement this after I fix the memory issue. But should be that hard I guess.

**Comment by mregni** [comment]
FYI, I just fixed the memory issue (partially) so next thing will be implementing the --no-update flag

**Comment by aptalca** [comment]
Implemented in the [latest version](https://github.com/linuxserver/docker-embystat/commit/bc29af0edb102cb46e251a9aa4261bed4cdb395a). Seems to work well. 

Thanks so much.
