### ISSUE TITLE
[FeatureReq] Armhf (arm32) binary

### ISSUE THREAD

**Issue by aptalca** [mregni/EmbyStat#961]
# Feature request

Hi,

[LinuxServer.io](https://linuxserver.io) member here, maintaining our new EmbyStat image:
https://hub.docker.com/r/linuxserver/embystat
https://github.com/linuxserver/docker-embystat

We are using a Jenkins pipeline to publish multi-arch docker images for various apps (some are endorsed by the upstream apps and we have close relationships with them, some we just publish on our own because we love FOSS). We'd like to publish multi-arch images for EmbyStat as well, however, there is currently no armhf binary published.

Our current image is x86 only, but, the aarch64 binary (linux-arm-x64) also works in an aarch64 based image when built locally: https://github.com/linuxserver/docker-embystat/blob/multi-arch/Dockerfile.aarch64

We'd like to request the addition of an armhf binary and we'd be happy to start publishing versioned multi-arch images for EmbyStat.

Thanks

**Comment by mregni** [comment]
Thanks for publishing my app. I just want to make sure, it really is still in beta so lot's of bugs are still present in the app. Also, the features are still bit limited but I'm working on it slowly.

First things first, let me have a look what armhf is and how I can create such a dotnet build. 

If there is anything else you need feel free to ask! More than happy to make EmbyStat run on multiple systems. But my knowledge is still limited about docker and hosting stuff.

**Comment by aptalca** [comment]
If you want to discuss those further, feel free to drop in to our discord: https://discord.gg/YWrKVTn
Ping me when you get in and we can get you into a private dev channel. We're working with some of the other devs with their switch to net core for their upstream apps

**Comment by thelamer** [comment]
When cross compiling `linux-arm64` is aarch64 and armhf is simply `linux-arm` (-r flag RID option)

**Comment by mregni** [comment]
Oke, thanks for the tip @thelamer. I'll add an extra build for linux-arm asap.

@aptalca, thanks for the discord. I will be gone for the weekend so probably going to contact you on Monday.

**Comment by mregni** [comment]
Hey guys, I just release a new beta version beta.13 and I included a linux-arm build (https://github.com/mregni/EmbyStat/releases/tag/0.2.0-beta.13). Let me know if the EmbyStat-linux-arm-v0.2.0-beta.13 build works correctly

**Comment by aptalca** [comment]
I did basic tests with starting it up and clicking on a few things in the UI. It seems to work fine on arm32.
Thanks.

We have a PR to enable multi-arch builds. When it's merged, user will be able to pull the same image on x86_64, arm or aarch64 and it will automatically retrieve the correct arch image.

**Comment by aptalca** [comment]
Although, I just noticed beta 13 is untagged as a release? Were there issues?

**Comment by mregni** [comment]
I made a mistake in my build pipeline. The updater exe was missing so updates were not working anymore. Fixed it and created a new release beta.13 with the correct files :)
Thanks for the help!

**Comment by aptalca** [comment]
Thanks for the heads up. We'll go ahead and merge the PR and release multi-arch then.
