### ISSUE TITLE
Cast with name of "Writer" appears as Most Featured Writer

### ISSUE THREAD

**Issue by cybergrimes** [mregni/EmbyStat#968]
**Describe the bug**
Movies page "Most Featured Writer" is a single person "Anna Akana" who appeared in the movie "Ant-Man (2015)" as "Writer". I checked IMDB on both the movie and her credits, she was not actually a writer for the movie. This appears to be what the role played in the film.

**To Reproduce**
1. Go to "Movies" tab
2. Scroll down to "Most featured" section

**Expected behavior**
I don't appear to have any actual writers in my Emby people details. 
I do not expect to see any most featured writer section.

**Screenshots**
https://imgur.com/a/hRnHcdo

**System (please complete the following information):**
- OS: Windows 10
- Browser: Microsoft Edge 
- Version: 78.0.276.20

**Additional context**
IMDB link for this person: https://www.imdb.com/name/nm4331196/
IMDB link for this film: https://www.imdb.com/title/tt0478970/

**Comment by mregni** [comment]
Thanks for logging this bug.
That's some very strange behaviour indeed! I'll see if I can fix this in the next beta.

**Comment by mregni** [comment]
Closing for now, since these stats are removed from the next build. I'll see if I can include these stats again in future releases.
