### ISSUE TITLE
CHECKUDPATE-JOB => No new version available

### ISSUE THREAD

**Issue by shenniko** [mregni/EmbyStat#980]
# Bug report
Hi, i can see that v0.2.0-beta.13 has been released, though when i check for an update I get:
10:19:23 12-11-19 JOB CONTROLLER => CHECKUDPATE-JOB job queued
10:19:29 12-11-19 CHECKUDPATE-JOB => Starting job
10:19:29 12-11-19 CHECKUDPATE-JOB => Contacting Github now to see if new version is available.
10:19:30 12-11-19 CHECKUDPATE-JOB => No new version available
10:19:30 12-11-19 CHECKUDPATE-JOB => Job finished after 1 minute.
 
**To Reproduce**
Goto Jobs and manually run the Check for new Updates Job.
Job Logs gives the message above

**Expected behavior**
As version 0.13 is out, im guessing that it should update.

**System (please complete the following information):**
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

- Browser Chrome

**Additional context**
Let me know if you need any more info

**Comment by mregni** [comment]
@shenniko, should find the update indeed. I'll have a look and report back to you this evening!

**Comment by mregni** [comment]
@shenniko, can you provide me with your log file as well?

**Comment by shenniko** [comment]
Log attached, not sure if there are any other logs, but thats the one it allows me to download on the GUI

[2019-11-12 (2).log](https://github.com/mregni/EmbyStat/files/3837457/2019-11-12.2.log)

**Comment by mregni** [comment]
Looks like my build process skipped the updater step, I'm rebuilding the project asap. I let you know when it's done.

**Comment by shenniko** [comment]
np, lemme know if you want me to change and test anything on my system

**Comment by mregni** [comment]
I just uploaded the new beta.13 with updater exe :) Feel free to test it

**Comment by shenniko** [comment]
Is there a particular file you want me to upload? or just upload/unzip the entire beta.13?

**Comment by mregni** [comment]
No, just try to update your beta.12 instance again the normal way. It worked on my machine just now. Let's hope it works on your machine as well

**Comment by shenniko** [comment]
Still getting:

20:20:33 12-11-19 JOB CONTROLLER => CHECKUDPATE-JOB job queued
20:20:46 12-11-19 CHECKUDPATE-JOB => Starting job
20:20:46 12-11-19 CHECKUDPATE-JOB => Contacting Github now to see if new version is available.
20:20:47 12-11-19 CHECKUDPATE-JOB => No new version available
20:20:47 12-11-19 CHECKUDPATE-JOB => Job finished after 1 minute.

**Comment by shenniko** [comment]
im also getting:

2019-11-12 20:20:42.3669 [ERROR] Error in event handler System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.TransactionService.PersistDirtyPages()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.InsertBulk(String collection, IEnumerable`1 docs, Int32 batchSize, BsonType autoId)
   at EmbyStat.Repositories.SessionRepository.InsertPlays(List`1 sessionPlays) in d:\a\1\s\EmbyStat.Repositories\SessionRepository.cs:line 45
   at EmbyStat.Services.SessionService.ProcessSessions(List`1 sessions) in d:\a\1\s\EmbyStat.Services\SessionService.cs:line 46
   at EmbyStat.Services.WebSocketService.WebSocketApiSessionsUpdated(Object sender, GenericEventArgs`1 e) in d:\a\1\s\EmbyStat.Services\WebSocketService.cs:line 107
   at EmbyStat.Clients.Emby.WebSocket.WebSocketApi.FireEvent[T](EventHandler`1 handler, Object sender, T args) in d:\a\1\s\EmbyStat.Clients.Emby.WebSocket\WebSocketApi.cs:line 212

a lot

**Comment by mregni** [comment]
And what happens when you go to the settings page -> update tab and trigger an update there

I saw that exception in your logs as well, but that is a problem with the sessions and I still need to fix that anyway. You should be able to update normally

**Comment by shenniko** [comment]
No update available

Current version: 0.2.0-beta.12

**Comment by mregni** [comment]
oke, the best thing you can do is remove the beta.12 version and just install a newly beta.13. You will have to finish the wizard again, but you will not lose any data because no live statistics are saved at the moment.

**Comment by mregni** [comment]
another option is to remove the updateFiles folder and the *.ver file from the main folder if you didn't delete the beta.12 instance already. Maybe that will fix your update problem.

**Comment by shenniko** [comment]
I already read option 1 and was working on that... so wiped, and now on version13.. will see what happens with next update :D

**Comment by mregni** [comment]
Oke that's good. I'll close the issue for now. If on the next release the update is still not working for you feel free to reopen it!
